#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the pre-bootstrap. Everything a factory-fresh Mac needs before the
# configuration repository exists on disk and can take over.
#
# Every phase is guarded: it checks whether its effect is already present and
# skips if so, which is what makes a re-run after an interrupted attempt cost
# seconds rather than starting over. Resumability is by guard, never by state
# file: a state file lies the moment something is fixed by hand.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# The library sets -euo pipefail. Add errtrace on top: without it the ERR trap
# below is not inherited by functions, and every action here is a function, so
# a failure would exit silently.
set -E

# ── Configuration ─────────────────────────────────────────────────────────
# Each of these is a seam: where this wizard reaches the machine. Overriding
# one points the wizard at somewhere else, which is how the tests describe a
# machine without owning one.

NIXPKGS_FLAKE="${NIXPKGS_FLAKE:-github:NixOS/nixpkgs/nixpkgs-unstable}"
NIX_INSTALLER_URL="${NIX_INSTALLER_URL:-https://nixos.org/nix/install}"
NIX_DAEMON_PROFILE="${NIX_DAEMON_PROFILE:-/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh}"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519}"
CLT_RECEIPT="com.apple.pkg.CLTools_Executables"
ROSETTA_RECEIPT="com.apple.pkg.RosettaUpdateAuto"
CLT_TIMEOUT="${CLT_TIMEOUT:-1800}"

# The file the cloned repository must provide for this wizard to hand over to.
HANDOFF="bootstrap.sh"

DRY_RUN=0
SLUG=""
DEST=""
PHASE_N=0
CURRENT_PHASE="startup"
SUDO_PRIMED=0

# A guard that wants to explain itself sets SKIP_REASON, which phase() reads
# once and clears. Only the guards with something to add beyond "already done"
# bother: Rosetta on Intel, and Nix already on PATH.
SKIP_REASON=""

# ── Plumbing ──────────────────────────────────────────────────────────────

usage() {
  cat <<USAGE
work-mac-bootstrap — take a factory-fresh Mac to a cloned configuration.

  bootstrap.sh [options] [owner/repo]

  owner/repo    the configuration repository to clone and hand over to.
                This wizard knows nothing else about it, and it is the only
                argument the wizard takes. Leave it out and the wizard lists
                your repositories after you sign in, and asks which one.

Options:
  -n, --dry-run   print the plan and exit, executing nothing
  -h, --help      show this help

Typical use, pinned to a release tag:

  curl -fsSL https://raw.githubusercontent.com/atthepit/work-mac-bootstrap/v1/bootstrap.sh \\
    | bash -s -- owner/repo
USAGE
}

die() {
  printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

have() { command -v "$1" >/dev/null 2>&1; }

is_repository() {
  [[ "$1" =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$ ]]
}

# The slug can arrive as an argument or be chosen part-way through the run, so
# the destination is derived rather than fixed at startup.
set_destination() {
  DEST="$HOME/${SLUG##*/}"
}

# Where the clone will land, for a plan written before the answer is known.
destination_display() {
  if [[ -n "$DEST" ]]; then
    printf '%s' "$DEST"
  else
    printf '%s/<the repository you choose>' "$HOME"
  fi
}

# nix_run ATTR ARGS... runs a package from nixpkgs without installing it. The
# pre-bootstrap owns no tooling: everything it needs is ephemeral, so the
# configuration remains the only thing that installs anything.
nix_run() {
  local attr="$1"; shift
  nix --extra-experimental-features 'nix-command flakes' \
    run "${NIXPKGS_FLAKE}#${attr}" -- "$@"
}

# gh_cli prefers a gh the machine already has, and fetches an ephemeral one
# only when there is none. A factory-fresh Mac has none; a machine part-way
# through a rebuild often does, and using it costs nothing.
gh_cli() {
  if have gh; then
    gh "$@"
  else
    nix_run gh "$@"
  fi
}

# can_ask_gh says whether this run may consult gh at all. A dry run downloads
# nothing and makes nobody wait, so it will use a gh that is already here but
# will not fetch one: where it cannot ask, the guard reads as unmet and the
# phase is reported as needed, which is the honest answer.
can_ask_gh() {
  if have gh; then return 0; fi
  if (( DRY_RUN )); then return 1; fi
  have nix
}

# ensure_sudo asks for the password once, up front, rather than letting an
# installer surprise you with a prompt halfway through a download. The two
# phases that need root run back to back, and each sudo call refreshes the
# grant, so one prompt covers both.
ensure_sudo() {
  if (( SUDO_PRIMED )); then return 0; fi
  warn "This step needs administrator rights."
  say "Enter your macOS login password. You are asked once."
  sudo -v
  SUDO_PRIMED=1
}

on_error() {
  local code=$?
  printf '\n  %s✗ %s failed (exit %s)%s\n' "$RED" "$CURRENT_PHASE" "$code" "$RESET" >&2
  printf '  %sEvery step checks whether it is already done, so running the same\n' "$DIM" >&2
  printf '  command again is safe and picks up where this one stopped.%s\n\n' "$RESET" >&2
  exit "$code"
}

trap on_error ERR

# ── Arguments ─────────────────────────────────────────────────────────────

while (( $# )); do
  case "$1" in
    -n|--dry-run) DRY_RUN=1 ;;
    -h|--help) usage; exit 0 ;;
    -*) usage >&2; die "unknown option: $1" ;;
    *)
      if [[ -n "$SLUG" ]]; then
        usage >&2
        die "unexpected argument: $1"
      fi
      SLUG="$1"
      ;;
  esac
  shift
done

if [[ -n "$SLUG" ]] && ! is_repository "$SLUG"; then
  usage >&2
  die "'$SLUG' is not a repository; name it as owner/repo"
fi

if [[ "$(uname -s)" != Darwin ]]; then
  die "this wizard only runs on macOS"
fi

if [[ -n "$SLUG" ]]; then
  set_destination
fi

# Piping this script into bash leaves stdin consumed, so prompts would read
# EOF. Take input from the terminal instead, when this run has one to take.
# The subshell asks whether the terminal can be opened at all: a failed
# redirection on exec would otherwise end the script.
if (( ! DRY_RUN )) && [[ ! -t 0 ]] && ( exec < /dev/tty ) 2>/dev/null; then
  exec < /dev/tty
fi

# ── Announcing a phase ────────────────────────────────────────────────────

# announce renders one phase. In dry-run it prints a plan line: the phase
# identifier, whether it would run, the guard that decided, and what it would
# do. In a real run it opens a stage instead. The dry-run form is the contract
# the tests assert on, so keep it stable.
announce() {
  local id="$1" title="$2" status="$3" guard_text="$4" detail="$5"
  if (( DRY_RUN )); then
    printf '  [%2d] %-19s %s\n' "$PHASE_N" "$id" "$status"
    printf '        guard: %s\n' "$guard_text"
    printf '        %s\n\n' "$detail"
  else
    stage "$title"
    if [[ "$status" == SKIP ]]; then
      printf '  %s✓ %s%s\n' "$GREEN" "$detail" "$RESET"
    else
      say "$detail"
    fi
    note "guard: $guard_text"
    printf '\n'
  fi
}

# phase ID TITLE GUARD_TEXT DETAIL GUARD_FN ACTION_FN evaluates the guard,
# announces the outcome, and runs the action only when the guard is unmet and
# this is not a dry run. Guards read the machine and change nothing, so
# evaluating them during a dry run is safe.
phase() {
  local id="$1" title="$2" guard_text="$3" detail="$4" guard_fn="$5" action_fn="$6"
  PHASE_N=$((PHASE_N + 1))
  SKIP_REASON=""
  if "$guard_fn"; then
    announce "$id" "$title" SKIP "$guard_text" "${SKIP_REASON:-already done}"
    return 0
  fi
  announce "$id" "$title" RUN "$guard_text" "$detail"
  if (( DRY_RUN )); then return 0; fi
  CURRENT_PHASE="$title"
  "$action_fn"
}

# ── Guards ────────────────────────────────────────────────────────────────

guard_command_line_tools() {
  xcode-select -p >/dev/null 2>&1 && pkgutil --pkg-info="$CLT_RECEIPT" >/dev/null 2>&1
}

guard_rosetta() {
  if [[ "$(uname -m)" != arm64 ]]; then
    SKIP_REASON="this Mac is not Apple Silicon, so Rosetta is not needed"
    return 0
  fi
  pkgutil --pkg-info="$ROSETTA_RECEIPT" >/dev/null 2>&1
}

guard_nix() {
  have nix || [[ -e "$NIX_DAEMON_PROFILE" ]]
}

guard_nix_profile() {
  if have nix; then
    SKIP_REASON="nix is already on this shell's PATH"
    return 0
  fi
  return 1
}

guard_github_auth() {
  can_ask_gh || return 1
  gh_cli auth status >/dev/null 2>&1
}

guard_git_credentials() {
  have git || return 1
  git config --global --get "credential.https://github.com.helper" 2>/dev/null | grep -q .
}

guard_ssh_key() {
  [[ -f "$SSH_KEY" && -f "$SSH_KEY.pub" ]] || return 1
  can_ask_gh || return 1
  local fingerprint
  fingerprint=$(ssh-keygen -lf "$SSH_KEY.pub" 2>/dev/null | awk '{print $2}') || return 1
  [[ -n "$fingerprint" ]] || return 1
  gh_cli ssh-key list 2>/dev/null | grep -qF "$fingerprint"
}

guard_choose_repository() {
  if [[ -n "$SLUG" ]]; then
    SKIP_REASON="$SLUG was named on the command line"
    return 0
  fi
  return 1
}

guard_clone() {
  [[ -n "$DEST" && -d "$DEST/.git" ]]
}

# The handoff is the point of the wizard, so it never reports as done.
guard_handoff() { return 1; }

# ── Actions ───────────────────────────────────────────────────────────────

do_command_line_tools() {
  say "A macOS dialog is opening. Click Install and accept the licence."
  xcode-select --install >/dev/null 2>&1 || true
  local waited=0
  until pkgutil --pkg-info="$CLT_RECEIPT" >/dev/null 2>&1; do
    sleep 5
    waited=$((waited + 5))
    if (( waited % 60 == 0 )); then
      note "still waiting for the Command Line Tools (${waited}s)"
    fi
    if (( waited >= CLT_TIMEOUT )); then
      die "the Command Line Tools did not finish installing; re-run when they have"
    fi
  done
  printf '  %s✓ Command Line Tools installed%s\n' "$GREEN" "$RESET"
}

do_rosetta() {
  ensure_sudo
  sudo softwareupdate --install-rosetta --agree-to-license
}

do_nix() {
  ensure_sudo
  say "Installing Nix. This takes a few minutes and needs no input."
  curl -fsSL "$NIX_INSTALLER_URL" | sh -s -- --daemon --yes
}

do_nix_profile() {
  [[ -e "$NIX_DAEMON_PROFILE" ]] ||
    die "Nix installed but $NIX_DAEMON_PROFILE is missing; open a new terminal and re-run"
  # The daemon profile is not written to our standards; read it leniently.
  set +u
  # shellcheck source=/dev/null
  . "$NIX_DAEMON_PROFILE"
  set -u
  have nix || die "sourcing $NIX_DAEMON_PROFILE did not put nix on PATH"
}

do_github_auth() {
  say "A browser window is opening with a one-time code to enter."
  gh_cli auth login \
    --hostname github.com \
    --git-protocol ssh \
    --web \
    --scopes admin:public_key
}

do_git_credentials() {
  gh_cli auth setup-git --hostname github.com
}

do_ssh_key() {
  if [[ ! -f "$SSH_KEY" ]]; then
    mkdir -p "$(dirname "$SSH_KEY")"
    chmod 700 "$(dirname "$SSH_KEY")"
    ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -C "$(whoami)@$(machine_name)"
  fi
  if ! gh_cli ssh-key add "$SSH_KEY.pub" --title "$(machine_name)"; then
    warn "GitHub refused the key; asking for the permission to add one."
    gh_cli auth refresh --hostname github.com --scopes admin:public_key
    gh_cli ssh-key add "$SSH_KEY.pub" --title "$(machine_name)"
  fi
}

do_choose_repository() {
  local repos=() line
  while IFS= read -r line; do
    if [[ -n "$line" ]]; then repos+=("$line"); fi
  done < <(gh_cli repo list --limit 100 --json nameWithOwner \
    --jq '.[].nameWithOwner' 2>/dev/null || true)

  local count=${#repos[@]}
  if (( count )); then
    printf '\n'
    local i=1
    for line in "${repos[@]}"; do
      printf '  %s%3d%s  %s\n' "$BLUE" "$i" "$RESET" "$line"
      i=$((i + 1))
    done
    printf '\n'
  else
    warn "GitHub listed no repositories, so name the one you want."
  fi

  local answer=""
  while :; do
    printf '  %sNumber from the list, or owner/repo:%s ' "$BOLD" "$RESET"
    if ! read -r answer; then
      die "no answer given; name the repository as an argument instead"
    fi
    # A repository you do not own is not on this list, so a typed owner/repo
    # is always accepted too.
    if [[ "$answer" =~ ^[0-9]+$ ]] && (( 10#$answer >= 1 && 10#$answer <= count )); then
      SLUG="${repos[$((10#$answer - 1))]}"
      break
    fi
    if is_repository "$answer"; then
      SLUG="$answer"
      break
    fi
    warn "Not a number on the list, and not an owner/repo."
  done

  set_destination
  printf '  %s✓ %s, cloning into %s%s\n' "$GREEN" "$SLUG" "$DEST" "$RESET"
}

do_clone() {
  gh_cli repo clone "$SLUG" "$DEST"
}

do_handoff() {
  [[ -f "$DEST/$HANDOFF" ]] ||
    die "$DEST/$HANDOFF does not exist; $SLUG does not provide a bootstrap to hand over to"
  printf '  %s→ handing over to %s%s\n\n' "$BLUE" "$DEST/$HANDOFF" "$RESET"
  # Hand over from inside the clone: what takes over is a configuration, and a
  # configuration is entitled to assume it is being run from its own root.
  cd "$DEST"
  if [[ -x "$DEST/$HANDOFF" ]]; then
    exec "$DEST/$HANDOFF"
  fi
  exec /bin/bash "$DEST/$HANDOFF"
}

machine_name() {
  scutil --get ComputerName 2>/dev/null || hostname
}

# The handoff target does not exist until the configuration repository
# provides it, so say so in the plan rather than at the last moment.
handoff_detail() {
  if [[ -z "$DEST" ]]; then
    printf 'exec %s/%s, from the clone' "$(destination_display)" "$HANDOFF"
    return 0
  fi
  if [[ -d "$DEST/.git" && ! -f "$DEST/$HANDOFF" ]]; then
    printf 'exec %s from %s — warning: the clone does not contain %s' \
      "$DEST/$HANDOFF" "$DEST" "$HANDOFF"
  else
    printf 'exec %s, from %s' "$DEST/$HANDOFF" "$DEST"
  fi
}

# ── The plan ──────────────────────────────────────────────────────────────

if (( DRY_RUN )); then
  printf '\n  %swork-mac-bootstrap — plan%s\n' "$BOLD" "$RESET"
  printf '  %srepository:  %s%s\n' \
    "$DIM" "${SLUG:-chosen from your GitHub account after sign-in}" "$RESET"
  printf '  %sclone into:  %s%s\n' "$DIM" "$(destination_display)" "$RESET"
  printf '  %shand over to %s/%s%s\n\n' \
    "$DIM" "$(destination_display)" "$HANDOFF" "$RESET"
else
  # The library's banner() describes a wizard that captures values you copy out
  # of a browser. This one installs things, so it says so in its own words.
  _clear
  printf '\n%s%s  work-mac-bootstrap%s\n' "$BOLD" "$BLUE" "$RESET"
  printf '%s  %s stages, taking this Mac to a clone of %s%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "${SLUG:-a configuration you choose}" "$RESET"
  printf '%s  Steps already done are skipped, and stopping with Ctrl-C costs you\n' "$DIM"
  printf '  nothing: run the same command again to pick up where you left off.%s\n\n' "$RESET"
  pause "Ready to start?"
fi

phase command-line-tools "Command Line Tools" \
  "xcode-select -p, and pkgutil --pkg-info=$CLT_RECEIPT" \
  "xcode-select --install, then poll for the package receipt until it lands" \
  guard_command_line_tools do_command_line_tools

phase rosetta "Rosetta 2" \
  "pkgutil --pkg-info=$ROSETTA_RECEIPT on Apple Silicon" \
  "softwareupdate --install-rosetta, accepting the licence" \
  guard_rosetta do_rosetta

phase nix "Nix" \
  "nix on PATH, or $NIX_DAEMON_PROFILE" \
  "install Nix from $NIX_INSTALLER_URL in daemon mode, unattended" \
  guard_nix do_nix

phase nix-profile "Nix in this shell" \
  "nix on PATH" \
  "source the daemon profile, so this run gains nix without a new terminal" \
  guard_nix_profile do_nix_profile

phase github-auth "GitHub sign-in" \
  "gh auth status" \
  "sign in to GitHub in the browser with a one-time code" \
  guard_github_auth do_github_auth

phase git-credentials "Git credential helper" \
  "git config --global credential.https://github.com.helper" \
  "point git at that sign-in, so pushing from this Mac needs nothing further" \
  guard_git_credentials do_git_credentials

phase ssh-key "SSH key" \
  "$SSH_KEY registered in gh ssh-key list" \
  "generate an ed25519 key and register it with GitHub" \
  guard_ssh_key do_ssh_key

phase choose-repository "Choose the configuration" \
  "a repository named on the command line" \
  "list the repositories on your GitHub account and ask which one to clone" \
  guard_choose_repository do_choose_repository

phase clone "Clone the configuration" \
  "$(destination_display)/.git" \
  "clone ${SLUG:-the repository you chose} into $(destination_display)" \
  guard_clone do_clone

phase handoff "Hand over to the configuration" \
  "never skipped" \
  "$(handoff_detail)" \
  guard_handoff do_handoff

if (( DRY_RUN )); then
  printf '  %sNothing was executed. Drop --dry-run to work through the plan.%s\n\n' \
    "$DIM" "$RESET"
fi
